### ISSUE TITLE
能不能加个空格暂停/播放的快捷键？每次用鼠标不太方便，谢谢！

### ISSUE THREAD

**Issue by yigexuezha** [xxxily/h5player#273]
能不能加个空格暂停/播放的快捷键？每次用鼠标不太方便，谢谢！

**Comment by JAGulin** [comment]
Space is already play/pause.
https://github.com/xxxily/h5player/blob/37c37dd2fd439b3d2fdd8d15ecccf2e4a8e208ef/src/h5player/index.js#L927
I'm not sure why it's not included in the list of shortcuts.
https://github.com/xxxily/h5player#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%88%97%E8%A1%A8

What site are you on, where it doesn't work?
Note that you may need to click to focus on the video, otherwise the key-press is handled by someone else.
