### ISSUE TITLE
[BUG] key up/down doesn't scroll window as spected

### ISSUE THREAD

**Issue by fclotet** [xxxily/h5player#300]
1. **Problem Description**
Key up/down doesn't scroll window as expected, the script doesn't take in count the context (selected or not the video) or if there is or not a video in page.
Even, normal keys are being override: for example alt+d, ctrl+c, ctrl+f

2. **Address where the above problem occurred**
Examples wrong working:
https://www.google.com/search?q=mosnters+&sxsrf=AOaemvJo1l88eooHrrwxQUKV1qSKqgKZYw%3A1631058981816&source=hp&ei=Jfw3YYzYLtLH5OUPxsajoAo&iflsig=ALs-wAMAAAAAYTgKNec74PdRYuSTyqupFivVN_50Y1om&oq=mosnters&gs_lcp=Cgdnd3Mtd2l6EAMyCgguEAoQywEQkwIyBwguEAoQywEyBwgAEAoQywEyBwgAEAoQywEyBwguEAoQywEyBAgAEAoyBAgAEAoyBAgAEAoyBAguEAoyBAgAEAo6BAgjECc6BQgAEJECOgsILhCABBDHARDRAzoFCAAQgAQ6BQguEIAEOgQIABBDOgsILhCABBDHARCjAjoLCC4QgAQQxwEQrwE6BwgAEIAEEApQqhdYhx9goihoAHAAeACAAa8BiAHzB5IBAzIuNpgBAKABAQ&sclient=gws-wiz&ved=0ahUKEwjM_tyZiO7yAhXSI7kGHUbjCKQQ4dUDCAc&uact=5
https://www.youtube.com/
Even with "caret browsing" scroll stops working (https://support.google.com/chrome/answer/10129654?hl=en)

3. **Information about the browser and browser version you are using**
Google Chrome V92.0.4515.159 (Build oficial) (64 bits)
ScriptVersion: 3.3.9

4. **Other additional information**
I was using the extension before and i think is amaizing some thigs like changing velocity, picture in picture, and others... but is really disturbing how the script overwride the standards keys.
My original language is Spanish, but my browser is in English.

Regards, Fidel

**Comment by fclotet** [comment]
In my local i have added the present code... I do a "valvule" that is opened/closed with the key ctrl+alt+z.

When te valvule is opened the key interpretation for h5Player continue, if it is closed h5Player hotKeys are ignored.

The code added is the yellow one...
![2021-09-08 10_51_17-sugerenciaValvula](https://user-images.githubusercontent.com/765280/132522384-b5a0c34b-a4d1-4999-bc9e-f95025c6c768.png)

...
    continueKeyInterpeter: function (event, key) {
        const t = h5Player;
        if (!event.shiftKey && event.ctrlKey && event.altKey && !event.metaKey && key === 'z') {
            t.h5PlayerValvule = !!!t.h5PlayerValvule;
            debug.log(`continueKeyInterpeter：h5 Valvule now is ${t.h5PlayerValvule? 'opened': 'closed'}`);
            event.stopPropagation();
            event.preventDefault();
            return false;
        }
        return !!t.h5PlayerValvule;
    },
...
   palyerTrigger: function (player, event) {
...
      const key = event.key.toLowerCase();
      if (!t.continueKeyInterpeter(event, key)) {
          return;
      };
...

**Comment by JAGulin** [comment]
Some of this may be a bug, but other things are design decisions or misunderstandings. Let's try to figure out which is which and how to improve. (And by the way, I'm not maintainer here, just trying to sort out problems overall.)

Let me first say that I couldn't reproduce the "google search" problem. For me there is no video (only links) in the results and the script leaves up/down to the browser. Did you get a video tag in the results? 

I have Chrome v94, could you try that? What is your script manager, I run TamperMonkey 4.13.
Do you have any other plugins/scripts that might interfere with this one?

> normal keys are being override: for example alt+d, ctrl+c, ctrl+f

I don't think any of those are in the script. Since you know coding, can you breakpoint in keydownEvent and palyerTrigger functions to find out what happens, e.g. for ctrl-c. Where would it call stopPropagation?

>script doesn't take in count the context (selected or not the video) 

The design decision is to default to "global mode", where you're right . Check t.globalMode in code.
To toggle mode, use Ctrl-\ (however key code 220 doesn't exist on my keyboard, so you may find the same issue).

A workaround similar to what you suggested I think already exist if you search for t.enable. Toggle all input with Ctrl-space.

> or if there is or not a video in page.

The intention is to only activate commands when there is a video detected. Could you help debug why that's not the case for you?

`      if (!player) {
        // debug.log('无可用的播放，不执行相关操作')
        return
`

> Key up/down doesn't scroll window as expected

When all conditions are met, the design is to override up/down keys, that's true. If you don't want to toggle as mentioned above, you could (as a workaround for now) change the shortcut for volume in the code. 

> disturbing how the script overwride the standards keys.

I suppose the idea is to make the shortcuts as accessible as possible. It would be nice to have things more configurable though.

> My original language is Spanish, but my browser is in English.

Keyboard layout is tricky, so if you find that unexpected shortcuts trigger, check [http://keycode.info/](http://keycode.info/) to see which key the browser actually thinks you press.
