### ISSUE TITLE
[BUG] video files shrink to 1x1px whenever spacebar is pressed

### ISSUE THREAD

**Issue by alexchandel** [xxxily/h5player#307]
1. **问题描述**
If `location.href` = video file, like `http://example.com/test.webm`, then `<video>` shrinks to 1x1 px when spacebar is pressed.

2. **出现上述问题的地址**
* Example: https://dl8.webmfiles.org/big-buck-bunny_trailer.webm
* Example: https://dl8.webmfiles.org/elephants-dream.webm

3. **你使用的浏览器与浏览器版本信息**
Chrome, newest.

4. **其他附注信息**
None.

**Comment by JAGulin** [comment]
A quick workaround for you is to enter full screen (e.g. Shift-Enter), which I think is a good idea anyway. 
----
As for details in the bug report, this is caused by the "tips message" style not working well with this (default) page. So it happens not only with play/pause, but also for some other commands as well as automatically on "playback position restored" etc. 

It's not limited to webm, but any video loaded directly.
[http://haignet.co.uk/html5-video-element-test.mp4](http://haignet.co.uk/html5-video-element-test.mp4)
Note: this is not linked to a specific domain either, the basic container "web page" is generated by the browser.

The problem seems to appear on Chrome and new Edge, but for some reason Firefox works fine even if the HTML is the same. I would guess it's not specific to the newest version either, but it might change since different browsers work differently.

**Comment by xxxily** [comment]
> 1. **问题描述**
>    If `location.href` = video file, like `http://example.com/test.webm`, then `<video>` shrinks to 1x1 px when spacebar is pressed.
> 2. **出现上述问题的地址**
> 
> * Example: https://dl8.webmfiles.org/big-buck-bunny_trailer.webm
> * Example: https://dl8.webmfiles.org/elephants-dream.webm
> 
> 3. **你使用的浏览器与浏览器版本信息**
>    Chrome, newest.
> 4. **其他附注信息**
>    None.

最新版已修复该问题
